// Generated by `npm run claims:apply` from Mohamed's notes. To change it,
// change the notes and run the command again; do not edit this file by hand.
import type { Bridge } from './types';

export const bridges: readonly Bridge[] = [
  {
    id: 'br-regulated-finance',
    phrases: [
      'regulated environment',
      'financial services',
      'banking',
      'compliance',
      'audit',
      'fintech',
      'RegTech',
      'KYC',
    ],
    strength: 'direct',
    statement:
      'He has worked in regulated financial-services environments: at BASS he built and supported Documentum workflows, DQL validation and PDF services for banking clients, where documents carry personal data, and his research is on detecting PII in text.',
    limit:
      'Not fintech product engineering; his banking work was enterprise content management for banking clients.',
    basisIds: [
      'project-documentum-workflows',
      'page-the-problem-documentum-workflows',
      'stack-pdf-utilities',
      'asc-pie-label-standardization',
      'architecture-asc-pie',
    ],
  },
  {
    id: 'br-document-ai',
    phrases: [
      'document AI',
      'document intelligence',
      'intelligent document processing',
      'IDP',
      'document understanding',
      'unstructured data',
      'PDFs',
      'forms',
      'claims',
      'contracts',
      'redaction',
    ],
    strength: 'direct',
    statement:
      'He covers both halves of document AI: PII extraction research (ASC-PIE and SPRINT-PP) and enterprise document workflows (Documentum intake, routing and retention, DQL validation, iText PDF assembly), plus OCR in Mind’s Eye and PDF ingestion in Northstar.',
    limit:
      'The site does not show layout models such as LayoutLM or Donut, or PDF redaction.',
    basisIds: [
      'project-documentum-workflows',
      'research-abstract',
      'minds-eye-ocr-speech',
      'stack-pdf-utilities',
      'project-northstar-rag',
      'project-asc-pie',
    ],
  },
  {
    id: 'br-information-extraction',
    phrases: [
      'information extraction',
      'named entity recognition',
      'NER',
      'token classification',
      'span extraction',
      'entity extraction',
      'text analytics',
    ],
    strength: 'direct',
    statement:
      'Information extraction is his specialism: a 19-type PII schema, a 333,109-example corpus, synchronized IOB2, key-value and JSON representations, and strict and normalized span-level F1.',
    basisIds: [
      'features-asc-pie',
      'stats-asc-pie',
      'research-abstract',
      'asc-pie-label-standardization',
    ],
  },
  {
    id: 'br-evaluation',
    phrases: [
      'evaluation framework',
      'evals',
      'benchmark',
      'benchmarking',
      'model evaluation',
      'LLM evaluation',
      'AI quality',
      'test harness',
      'metrics',
    ],
    strength: 'direct',
    statement:
      'His thesis is an evaluation framework: one schema, one parser and one scorer across encoder, encoder-decoder and decoder-only models, with output validity, strict and normalized F1, latency, robustness and continual-learning metrics.',
    basisIds: [
      'page-what-mohamed-built-asc-pie-1',
      'research-abstract',
      'architecture-asc-pie',
    ],
  },
  {
    id: 'br-rag',
    phrases: [
      'RAG',
      'retrieval-augmented generation',
      'vector search',
      'vector database',
      'embeddings',
      'grounding',
      'citations',
      'hallucination',
      'guardrails',
    ],
    strength: 'direct',
    statement:
      'Northstar is his independently built grounded RAG service: chunking, local embeddings, a vector store, a distance threshold that triggers a refusal before generation, and provenance on every answer. This site’s own assistant is a second grounded system he built.',
    limit:
      'Both are personal projects, not production deployments for an employer.',
    basisIds: [
      'features-northstar-rag',
      'project-northstar-rag',
      'page-what-mohamed-would-do-next-northstar-rag',
      'northstar-api-deployment',
    ],
  },
  {
    id: 'br-llm-work',
    phrases: [
      'LLM',
      'large language models',
      'generative AI',
      'GenAI',
      'prompt engineering',
      'fine-tuning',
      'in-context learning',
      'open-weight models',
    ],
    strength: 'direct',
    statement:
      'His thesis fine-tuned and prompted open-weight LLMs (Llama 3.1-8B and Qwen2.5-7B) and compared fine-tuning with in-context learning across output protocols and shot counts.',
    limit: 'The site does not show a production LLM product he operated.',
    basisIds: [
      'research-prompting-vs-fine-tuning',
      'research-model-families',
      'page-what-mohamed-would-do-next-asc-pie',
      'page-outcome-asc-pie-3',
      'research-rq2',
      'page-the-problem-northstar-rag',
    ],
  },
  {
    id: 'br-ml-lifecycle',
    phrases: [
      'end-to-end ML lifecycle',
      'model development',
      'feature engineering',
      'model deployment',
      'ML pipelines',
      'own the lifecycle',
    ],
    strength: 'direct',
    statement:
      'At DotPy he took applied ML projects from scoping and data preparation through feature engineering, model selection and evaluation to delivery as notebooks, API services or Dockerized prototypes. His York research covered dataset construction, fine-tuning, inference and evaluation.',
    basisIds: [
      'applied-ml-portfolio-lifecycle',
      'project-asc-pie',
      'page-what-mohamed-built-applied-ml-portfolio-6',
      'page-what-mohamed-learned-asc-pie',
      'page-what-mohamed-built-applied-ml-portfolio-1',
      'passport-applied-ml-portfolio',
    ],
  },
  {
    id: 'br-production-ml',
    phrases: [
      'production ML systems',
      'models in production',
      'monitoring',
      'drift',
      'serving at scale',
    ],
    strength: 'related',
    statement:
      'His ML delivery was as API services and Dockerized prototypes with handover, and he integrated model endpoints with mobile and backend teams. The site does not show models he operated at large production scale.',
    basisIds: [
      'applied-ml-portfolio-lifecycle',
      'page-what-mohamed-would-do-next-minds-eye',
      'page-what-mohamed-built-applied-ml-portfolio-3',
      'minds-eye-purpose',
      'features-dive',
    ],
  },
  {
    id: 'br-applied-data-science',
    phrases: [
      'forecasting',
      'customer segmentation',
      'recommendation',
      'fraud detection',
      'sentiment analysis',
      'churn',
      'predictive modelling',
      'data science',
    ],
    strength: 'direct',
    statement:
      'His applied ML projects at DotPy covered forecasting, customer segmentation, recommendation, sentiment and emotion analysis, fraud detection under class imbalance, and image classification. Project metrics were not preserved.',
    basisIds: [
      'page-what-mohamed-built-applied-ml-portfolio-1',
      'applied-ml-portfolio-purpose',
      'passport-applied-ml-portfolio',
    ],
  },
  {
    id: 'br-privacy-engineering',
    phrases: [
      'privacy',
      'data protection',
      'PII',
      'de-identification',
      'anonymization',
      'data governance',
      'retention',
      'PIPEDA',
      'GDPR',
      'privacy by design',
    ],
    strength: 'direct',
    statement:
      'His privacy work is engineering: a 19-type PII schema, PII extraction models, continual learning that avoids storing raw PII, synthetic generation of rare identifiers, and Documentum retention and archival workflows.',
    limit:
      'The site does not show a formal privacy-policy, legal or governance role.',
    basisIds: [
      'research-abstract',
      'page-his-role-asc-pie',
      'page-what-mohamed-built-documentum-workflows',
      'page-overview-sprint-pp',
      'page-the-problem-sprint-pp-2',
      'page-what-mohamed-built-asc-pie-2',
    ],
  },
  {
    id: 'br-java-backend',
    phrases: [
      'Java',
      'backend',
      'REST APIs',
      'Spring Boot',
      'services',
      'integration',
      'API development',
      'SQL',
    ],
    strength: 'direct',
    statement:
      'At BASS he built Java and Python services and internal REST endpoints, with JSON contracts, authentication flows, structured logging and production support, alongside Documentum and PDF utilities.',
    limit:
      'The site does not show large microservice platforms or event streaming such as Kafka.',
    basisIds: [
      'project-rest-pocs',
      'page-what-mohamed-learned-pdf-utilities',
      'page-what-mohamed-built-pdf-utilities',
      'documentum-workflows-stack',
      'features-cloud-backend',
      'rest-pocs-stack',
    ],
  },
  {
    id: 'br-ecm',
    phrases: [
      'Documentum',
      'OpenText',
      'enterprise content management',
      'ECM',
      'records management',
      'content server',
      'DQL',
      'document lifecycle',
    ],
    strength: 'direct',
    statement:
      'He implemented OpenText Documentum workflows and lifecycles for intake, review, routing, archival and retention, with DQL validation and production support, for banking clients.',
    basisIds: ['project-documentum-workflows', 'career-bass'],
  },
  {
    id: 'br-android',
    phrases: [
      'Android',
      'Kotlin',
      'mobile development',
      'Play Console',
      'MVVM',
      'mobile engineer',
    ],
    strength: 'direct',
    statement:
      'He built Android apps for clients over five years in Kotlin and Java, with MVVM or MVP, Retrofit, Room, Firebase and Play Console releases. Jetpack Compose, Hilt and RxJava are exposure-level only.',
    basisIds: [
      'project-food-planner',
      'stack-weather-checker',
      'page-outcome-dostava',
      'decisions-weather-checker',
    ],
  },
  {
    id: 'br-mobile-ml',
    phrases: [
      'mobile ML',
      'on-device ML',
      'OCR',
      'computer vision',
      'edge AI',
      'assistive technology',
    ],
    strength: 'related',
    statement:
      'He has integrated OCR, computer vision and ML services into Android apps, most fully in Mind’s Eye (face, object and text recognition with spoken feedback, and an Egyptian currency recogniser he built himself). Computer vision is secondary to NLP in his work.',
    basisIds: [
      'stack-minds-eye',
      'page-outcome-minds-eye',
      'decisions-minds-eye',
      'decisions-dive',
      'page-the-problem-dive',
    ],
  },
  {
    id: 'br-client-facing',
    phrases: [
      'customer-facing',
      'client-facing',
      'proofs of concept',
      'PoC',
      'stakeholders',
      'implementation',
      'solutions engineering',
      'forward deployed',
      'consulting',
    ],
    strength: 'direct',
    statement:
      'He has delivered directly to clients: proofs of concept and REST contracts as an ECM consultant at BASS, client scoping and delivery as a freelance Android developer, and model-serving contracts with other teams at DotPy.',
    limit: 'The site does not show sales quotas or pre-sales roles.',
    basisIds: [
      'rest-pocs-purpose',
      'passport-applied-ml-portfolio',
      'applied-ml-portfolio-lifecycle',
      'dostava-no-download-metrics',
      'page-who-it-was-for-rest-pocs',
      'page-how-it-works-rest-pocs',
    ],
  },
  {
    id: 'br-teaching',
    phrases: [
      'teaching',
      'training',
      'curriculum',
      'instruction',
      'mentoring',
      'technical trainer',
      'workshops',
      'communication',
    ],
    strength: 'direct',
    statement:
      'He has taught since 2019: teaching assistant at York, private instruction in computer science, and workshops and coding clinics, with his own problem sets, mock exams and auto-graded labs.',
    basisIds: [
      'teaching-portfolio-1',
      'project-asc-pie',
      'teaching-computing-topics',
      'teaching-ai-ml',
      'teaching-portfolio-3',
    ],
  },
  {
    id: 'br-cs-fundamentals',
    phrases: [
      'computer science fundamentals',
      'data structures and algorithms',
      'problem solving',
      'coding interviews',
    ],
    strength: 'direct',
    statement:
      'He competed in ICPC for three consecutive years and has taught data structures and algorithms.',
    basisIds: [
      'icpc-contestant',
      'career-private-instructor',
      'teaching-ai-ml',
    ],
  },
  {
    id: 'br-research',
    phrases: [
      'research',
      'publications',
      'research engineer',
      'reproducible research',
      'experiments',
    ],
    strength: 'direct',
    statement:
      'His M.A. thesis is deposited in YorkSpace, and the SPRINT-PP paper is accepted to IEEE CASCON 2026. His research artifacts include dataset manifests, configurations, evaluation summaries and prediction traces.',
    limit: 'He does not hold a PhD.',
    basisIds: [
      'passport-sprint-pp',
      'features-asc-pie',
      'page-outcome-sprint-pp-1',
      'page-links-asc-pie',
    ],
  },
  {
    id: 'br-degree',
    phrases: [
      "master's degree",
      'graduate degree',
      'MSc or PhD preferred',
      'advanced degree',
    ],
    strength: 'direct',
    statement:
      'He holds a completed master’s degree: an M.A. in Information Systems & Technology from York University.',
    basisIds: [
      'asc-pie-degree-awarded',
      'passport-asc-pie',
      'page-what-mohamed-would-do-next-asc-pie',
    ],
  },
  {
    id: 'br-cloud',
    phrases: ['AWS', 'GCP', 'Azure', 'cloud platforms', 'cloud services'],
    strength: 'related',
    statement:
      'He has working knowledge of cloud platforms at project and coursework level, including cloud vision services in Mind’s Eye.',
    basisIds: [
      'project-minds-eye',
      'page-outcome-dive',
      'dive-cloud-and-location-services',
    ],
  },
  {
    id: 'br-containers-ci',
    phrases: ['Docker', 'containers', 'CI/CD', 'packaging', 'versioning'],
    strength: 'direct',
    statement:
      'He has used Docker and Docker Compose to package ML prototypes and the Northstar service, with CI/CD and versioning practice. Kubernetes is not part of his experience.',
    basisIds: [
      'northstar-api-deployment',
      'career-android-freelance',
      'page-how-it-works-northstar-rag-2',
    ],
  },
  {
    id: 'br-startup-breadth',
    phrases: [
      'startup',
      'ambiguity',
      'wear many hats',
      'ownership',
      'generalist',
      'self-directed',
    ],
    strength: 'related',
    statement:
      'His record shows end-to-end ownership across research, backend, mobile and teaching, and he currently works as a Founding AI Engineer at Eklan.',
    basisIds: [
      'career-eklan',
      'features-this-portfolio',
      'career-graduate-researcher',
      'minds-eye-purpose',
      'career-java-freelance',
    ],
  },
];
