// Generated by `npm run claims:apply` from Mohamed's notes. To change it,
// change the notes and run the command again; do not edit this file by hand.
import type { WordingRule } from './types';

export const wordingRules: readonly WordingRule[] = [
  {
    topic: 'Google Play',
    say: 'Use the site’s per-app status only. Never name or count which apps were on Google Play beyond what each project page states.',
    never: [],
  },
  {
    topic: 'DotPy role',
    say: 'AI & ML Specialist. He planned work, coordinated delivery and mentored juniors, with no direct reports.',
    never: ['Technical Manager, team lead, managed a team'],
  },
  {
    topic: 'DotPy delivery',
    say: 'Delivered as notebooks, API services and Dockerized prototypes with handover.',
    never: [
      'production deployment at scale, any project metric, any client or dataset name',
    ],
  },
  {
    topic: 'Dive planner',
    say: 'A client proof of concept he built. 99.5% is offline test accuracy for a decision tree; the app is a planning aid, not a safety device.',
    never: ['published, a safety guarantee, RGBM'],
  },
  {
    topic: 'Intrusion detection results',
    say: 'Lead with his skepticism about the near-perfect scores, not with the scores.',
    never: [],
  },
  {
    topic: 'Cloud platforms',
    say: 'Working knowledge at project and coursework level.',
    never: [],
  },
  {
    topic: 'Mind’s Eye',
    say: 'A five-person capstone. He delivered more than 80% of the system and built the currency recogniser himself.',
    never: [
      'sole author of the whole system, any accuracy figure for currency recognition',
    ],
  },
  {
    topic: 'SPRINT-PP privacy',
    say: 'Replay-free. It stores prototypes, not personal data. Not a formal privacy guarantee.',
    never: [],
  },
  {
    topic: 'Northstar',
    say: 'An independently built grounded RAG service over fictional documents; a personal project.',
    never: ['any RAGAS score, production deployment'],
  },
  {
    topic: 'Team and inherited projects',
    say: 'Follow the site’s status badge and ownership line for each project. Tic-Tac-Toe and Shop on the Go were team projects.',
    never: [
      'sole authorship of Gulf Arab Chat, SAMS, the school management system or the restaurant app',
    ],
  },
  {
    topic: 'Mercato Star Finder',
    say: 'Customised and extended.',
    never: [],
  },
  {
    topic: 'Degree',
    say: 'M.A. in Information Systems & Technology, York University, completed.',
    never: ['MSc, in progress'],
  },
  {
    topic: 'CEH',
    say: 'A training programme at Inspire Academy, 2022. No exam was taken.',
    never: [],
  },
];

export const unconfirmedClaims: readonly string[] = [
  'PEFT or LoRA',
  'PDF redaction',
  'Trello, Azure DevOps, formal Agile ceremonies at BASS',
  'Documentum D2, xCP or DFC depth',
  'A dataset name or a metric for any DotPy project',
  'Any description of what he does at Eklan beyond the title',
];

export const excludedTopics: readonly string[] = [
  'The lab collaboration he marked "spoken only"',
  'His job-search automation project',
  'Salary, references and their contact details (the hard guard already refuses)',
  'Fit ratings, shortlist odds and recruiter-findability figures from the role atlas',
];

export const namedGaps: readonly string[] = [
  'Kubernetes, distributed training, large-scale model serving',
  'Airflow, dbt, Kubeflow, feature stores, production MLflow',
  'XGBoost or LightGBM in production',
  'vLLM, DeepSpeed',
  'LangGraph, AutoGen or other agent frameworks in production',
  'A/B testing, causal inference, experimentation design',
  'TensorRT, ONNX, quantisation',
  'iOS, delivered Flutter or React Native apps',
  'React, Angular, front-end engineering',
  'Formal people management',
  'A PhD',
];

export const datedStatements: readonly { date: string; statement: string }[] = [
  {
    date: '2026-10-06',
    statement:
      'The SPRINT-PP paper is accepted to IEEE CASCON 2026. The folder still says "under review"; that is stale.',
  },
  {
    date: '2026-10-06',
    statement:
      'The BASS stack included Spring Boot, SOAP, Microsoft SQL Server and Oracle Database.',
  },
  {
    date: '2026-10-06',
    statement:
      "Mind's Eye used an ESP32 with the Arduino framework and a Bluetooth link to the phone. Your Life Is My Life was built in Java.",
  },
  {
    date: '2026-10-10',
    statement:
      'He works at Eklan as Founding AI Engineer, with a one-week notice period. The site and the assistant may say so.',
  },
];

export const sourcePrecedence: readonly string[] = [
  'The site as published (reviewed under the earlier briefs)',
  "Mohamed's own dated statements (below)",
  'This pack and question-bank.yaml',
  'The folder files',
];
