// `npm run claims:apply`: turns Mohamed's two note files into committed data.
// It reads the git-ignored YAML in "Claude outputs/claims-review/", checks every
// item against the site, writes src/data/claims/*.ts and lists what it held
// back. It makes no model call and reads nothing else from the private folder.
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { format, resolveConfig } from 'prettier';
import { getDocument } from 'pdfjs-dist/legacy/build/pdf.mjs';
import YAML from 'yaml';
import { numeralsIn } from '../src/lib/rag/claim-checks.ts';
import {
  buildSkillTiers,
  importBridges,
  importQuestionBank,
  importWordingRules,
  type HeldBack,
  type RawAnswer,
  type RawBridge,
  type RawSkillTiers,
  type RawWordingRule,
} from '../src/lib/rag/claim-import.ts';
import { buildSiteLedger } from './site-ledger.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const reviewDir = resolve(root, 'Claude outputs/claims-review');
const outDir = resolve(root, 'src/data/claims');
const resumeDir = resolve(root, 'public/resumes');

const RESUME_SOURCES: Record<string, string> = {
  'Mohamed-Hafez-AI-ML-Engineer.pdf': 'resume-aiml',
  'Mohamed-Hafez-Software-Engineer.pdf': 'resume-software',
  'Mohamed-Hafez-Android-Developer.pdf': 'resume-android',
  'Mohamed-Hafez-TA-Instructor.pdf': 'resume-teaching',
};

type Pack = {
  precedence: string[];
  mohamed_dated_statements: Array<{ date: string; statement: string }>;
  wording_rules: RawWordingRule[];
  unconfirmed_do_not_claim: string[];
  excluded_topics: string[];
  skill_tiers: RawSkillTiers;
  named_gaps: string[];
  bridges: RawBridge[];
};
type Bank = { meta: { approved: boolean }; answers: RawAnswer[] };

async function readYaml<T>(name: string): Promise<T> {
  try {
    return YAML.parse(await readFile(resolve(reviewDir, name), 'utf8')) as T;
  } catch (error) {
    throw new Error(
      `Cannot read ${name} in "Claude outputs/claims-review/": ${(error as Error).message}`,
    );
  }
}

async function resumeTexts() {
  const files = (await readdir(resumeDir)).filter((f) => f in RESUME_SOURCES);
  return Promise.all(
    files.sort().map(async (file) => {
      const data = new Uint8Array(await readFile(resolve(resumeDir, file)));
      const pdf = await getDocument({ data, disableWorker: true }).promise;
      const pages: string[] = [];
      for (let number = 1; number <= pdf.numPages; number++) {
        const content = await (await pdf.getPage(number)).getTextContent();
        pages.push(
          content.items
            .map((item) => ('str' in item ? item.str : ''))
            .join(' '),
        );
      }
      return { sourceId: RESUME_SOURCES[file]!, text: pages.join('\n') };
    }),
  );
}

async function writeData(
  file: string,
  imports: string,
  declarations: Array<{ name: string; type: string; value: unknown }>,
) {
  const body = declarations
    .map(
      ({ name, type, value }) =>
        `export const ${name}: ${type} = ${JSON.stringify(value, null, 2)};`,
    )
    .join('\n\n');
  const source = `// Generated by \`npm run claims:apply\` from Mohamed's notes. To change it,\n// change the notes and run the command again; do not edit this file by hand.\n${imports}\n\n${body}\n`;
  const path = resolve(outDir, file);
  const config = (await resolveConfig(path)) ?? {};
  await writeFile(path, await format(source, { ...config, filepath: path }));
}

function heldBackSection(title: string, items: string[]) {
  return [
    `## ${title}`,
    '',
    ...(items.length ? items : ['Nothing held back.']),
    '',
  ];
}

export async function applyClaims() {
  const [pack, bank, site, resumes] = await Promise.all([
    readYaml<Pack>('assistant-pack.yaml'),
    readYaml<Bank>('question-bank.yaml'),
    buildSiteLedger(),
    resumeTexts(),
  ]);

  const bridges = importBridges(pack.bridges, site);
  const tiers = buildSkillTiers(pack.skill_tiers, site, resumes);
  const answers = importQuestionBank(
    { approved: bank.meta.approved === true, answers: bank.answers },
    site,
  );

  await mkdir(outDir, { recursive: true });
  await writeData('bridges.ts', "import type { Bridge } from './types';", [
    { name: 'bridges', type: 'readonly Bridge[]', value: bridges.bridges },
  ]);
  await writeData(
    'skill-tiers.ts',
    "import type { SkillTierGroup } from './types';",
    [
      {
        name: 'skillTierGroups',
        type: 'readonly SkillTierGroup[]',
        value: tiers.groups,
      },
    ],
  );
  await writeData(
    'wording-rules.ts',
    "import type { WordingRule } from './types';",
    [
      {
        name: 'wordingRules',
        type: 'readonly WordingRule[]',
        value: importWordingRules(pack.wording_rules),
      },
      {
        name: 'unconfirmedClaims',
        type: 'readonly string[]',
        value: pack.unconfirmed_do_not_claim,
      },
      {
        name: 'excludedTopics',
        type: 'readonly string[]',
        value: pack.excluded_topics,
      },
      { name: 'namedGaps', type: 'readonly string[]', value: pack.named_gaps },
      {
        name: 'datedStatements',
        type: 'readonly { date: string; statement: string }[]',
        value: pack.mohamed_dated_statements,
      },
      {
        name: 'sourcePrecedence',
        type: 'readonly string[]',
        value: pack.precedence,
      },
    ],
  );
  await writeData(
    'question-bank.ts',
    "import type { BankAnswer } from './types';",
    [
      {
        name: 'questionBank',
        type: 'readonly BankAnswer[]',
        value: answers.answers,
      },
    ],
  );

  // Informational: numbers in an answer that no site claim shows.
  const siteNumbers = new Set(site.flatMap((claim) => numeralsIn(claim.text)));
  const unmatchedNumbers = answers.answers.flatMap((answer) => {
    const unmatched = numeralsIn(answer.answer).filter(
      (number) => !siteNumbers.has(number),
    );
    return unmatched.length ? [`- ${answer.id}: ${unmatched.join(', ')}`] : [];
  });

  const asLines = (items: HeldBack[]) =>
    items.map((item) => `- ${item.id}: ${item.reason}`);
  const report = [
    '# Held back by `npm run claims:apply`',
    '',
    'Items the import did not publish, and why. Nothing here was reworded.',
    '',
    ...heldBackSection('Bridges', asLines(bridges.heldBack)),
    ...heldBackSection(
      'Skills no site claim or public résumé mentions',
      tiers.heldBack.map((s) => `- ${s.area} / ${s.tier}: ${s.skill}`),
    ),
    ...heldBackSection('Answers', asLines(answers.heldBack)),
    ...heldBackSection(
      'Numbers in imported answers that no site claim shows (kept; for Mohamed to check)',
      unmatchedNumbers,
    ),
  ].join('\n');
  await writeFile(resolve(reviewDir, 'held-back.md'), `${report}\n`, 'utf8');

  return {
    bridges: `${bridges.bridges.length} of ${pack.bridges.length}`,
    skillGroups: tiers.groups.length,
    skillsHeldBack: tiers.heldBack.length,
    answers: `${answers.answers.length} of ${bank.answers.length}`,
    held: bridges.heldBack.length + answers.heldBack.length,
  };
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  const summary = await applyClaims();
  process.stdout.write(
    `Bridges ${summary.bridges}; skill groups ${summary.skillGroups} (${summary.skillsHeldBack} skills held back); answers ${summary.answers}; ${summary.held} bridges or answers held back. See "Claude outputs/claims-review/held-back.md".\n`,
  );
}
